# Generated by Django 4.2 on 2023-04-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(max_length=100)),
                ('predador', models.BooleanField(default=False)),
                ('venenoso', models.BooleanField(default=False)),
                ('domestico', models.BooleanField(default=False)),
            ],
        ),
    ]
